/** Builds docs/RUN_LOG.md from automation_runs + videos + reviews (§10 Phase 3 tracking). */

export interface RunRow {
  id: number;
  trigger: string;
  started_at: string;
  topic: string | null;
  video_id: number | null;
  outcome: string | null;
  duration_s: number | null;
  num_turns: number | null;
  input_tokens: number | null;
  output_tokens: number | null;
  cost_usd_equiv: number | null;
  permission_denials: number | null;
  error: string | null;
  video_status: string | null;
  first_decision: string | null;
}

export interface StepRow {
  step: string;
  runs: number;
  failures: number;
  avg_s: number | null;
}

const PRODUCING = (o: string | null) => o !== 'skip' && o !== 'locked' && o !== 'running';
const fmtMin = (s: number | null) => (s == null ? '' : `${(s / 60).toFixed(1)} min`);
const fmtK = (n: number | null) => (n == null ? '' : `${Math.round(n / 1000)}k`);
const cell = (s: string | null | undefined) => (s ?? '').replace(/\|/g, '/').replace(/\s+/g, ' ').slice(0, 80);

/** Longest run of successes at the end (scheduled only, skips don't break it) — the Phase 3 DoD counter. */
export function scheduledStreak(rows: RunRow[]): number {
  let n = 0;
  for (const r of [...rows].sort((a, b) => b.id - a.id)) {
    if (r.trigger !== 'scheduled' || !PRODUCING(r.outcome)) continue;
    if (r.outcome !== 'in_review') break;
    n++;
  }
  return n;
}

export function buildRunLog(rows: RunRow[], steps: StepRow[], now = new Date()): string {
  const producing = rows.filter((r) => PRODUCING(r.outcome));
  const ok = producing.filter((r) => r.outcome === 'in_review');
  const avg = (xs: (number | null)[]) => {
    const v = xs.filter((x): x is number => x != null);
    return v.length ? v.reduce((a, b) => a + b, 0) / v.length : null;
  };
  const decided = ok.filter((r) => r.first_decision);
  const firstTime = decided.filter((r) => r.first_decision === 'approved').length;

  const lines = [
    '# Run log',
    '',
    `Generated by \`npm run report\` on ${now.toISOString().slice(0, 16).replace('T', ' ')} UTC. Don't edit by hand.`,
    '',
    '## Summary',
    '',
    `- Runs that tried to make a video: **${producing.length}**, reached review: **${ok.length}**, failure rate: **${producing.length ? Math.round(((producing.length - ok.length) / producing.length) * 100) : 0}%**`,
    `- Skipped (queue full / no topics / another run going): ${rows.length - producing.length}`,
    `- Average time per successful video: **${fmtMin(avg(ok.map((r) => r.duration_s)))}**`,
    `- Average Claude usage per successful run: ${fmtK(avg(ok.map((r) => r.input_tokens)))} input tokens (mostly cache reads), ${fmtK(avg(ok.map((r) => r.output_tokens)))} output tokens, ≈ $${(avg(ok.map((r) => r.cost_usd_equiv)) ?? 0).toFixed(2)} API-equivalent (not billed on the subscription)`,
    `- Thomas approved first time: **${firstTime} of ${decided.length}** reviewed`,
    `- Consecutive successful scheduled runs (Phase 3 goal: 5): **${scheduledStreak(rows)}**`,
    '',
    '## Runs',
    '',
    '| # | When (UTC) | Trigger | Topic | Video | Outcome | Time | Turns | Tokens in/out | Denials | Review | Notes |',
    '|---|---|---|---|---|---|---|---|---|---|---|---|',
    ...[...rows]
      .sort((a, b) => b.id - a.id)
      .map(
        (r) =>
          `| ${r.id} | ${r.started_at.slice(0, 16)} | ${r.trigger} | ${cell(r.topic)} | ${r.video_id ?? ''} | ${r.outcome ?? ''} | ${fmtMin(r.duration_s)} | ${r.num_turns ?? ''} | ${fmtK(r.input_tokens)} / ${fmtK(r.output_tokens)} | ${r.permission_denials ?? ''} | ${r.first_decision ?? (r.video_status === 'in_review' ? 'waiting' : '')} | ${cell(r.outcome === 'in_review' ? '' : r.error)} |`,
      ),
    '',
    '## Pipeline steps (all videos)',
    '',
    '| Step | Runs | Failed | Avg time |',
    '|---|---|---|---|',
    ...steps.map((s) => `| ${s.step} | ${s.runs} | ${s.failures} | ${s.avg_s == null ? '' : `${Math.round(s.avg_s)} s`} |`),
    '',
  ];
  return lines.join('\n');
}
